/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LinksRouteImport } from './routes/links'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as navRouteRouteImport } from './routes/(nav)/route'
import { Route as navIndexRouteImport } from './routes/(nav)/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as navWorkWithMeRouteImport } from './routes/(nav)/work-with-me'
import { Route as navVideosRouteImport } from './routes/(nav)/videos'
import { Route as navTourRouteImport } from './routes/(nav)/tour'
import { Route as navLoginRouteImport } from './routes/(nav)/login'
import { Route as navContactRouteImport } from './routes/(nav)/contact'
import { Route as navMusicIndexRouteImport } from './routes/(nav)/music/index'
import { Route as navMembersIndexRouteImport } from './routes/(nav)/members/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as navMusicSlugRouteRouteImport } from './routes/(nav)/music/$slug/route'
import { Route as navMusicSlugIndexRouteImport } from './routes/(nav)/music/$slug/index'
import { Route as navAdminPostsIndexRouteImport } from './routes/(nav)/admin/posts/index'
import { Route as navMusicSlugTrackRouteImport } from './routes/(nav)/music/$slug/$track'
import { Route as navMembersPostSlugRouteImport } from './routes/(nav)/members/post/$slug'
import { Route as navAdminPostsNewRouteImport } from './routes/(nav)/admin/posts/new'
import { Route as navAdminPostsPostIdRouteImport } from './routes/(nav)/admin/posts/$postId'

const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const navRouteRoute = navRouteRouteImport.update({
  id: '/(nav)',
  getParentRoute: () => rootRouteImport,
} as any)
const navIndexRoute = navIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => navRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const navWorkWithMeRoute = navWorkWithMeRouteImport.update({
  id: '/work-with-me',
  path: '/work-with-me',
  getParentRoute: () => navRouteRoute,
} as any)
const navVideosRoute = navVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => navRouteRoute,
} as any)
const navTourRoute = navTourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => navRouteRoute,
} as any)
const navLoginRoute = navLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => navRouteRoute,
} as any)
const navContactRoute = navContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => navRouteRoute,
} as any)
const navMusicIndexRoute = navMusicIndexRouteImport.update({
  id: '/music/',
  path: '/music/',
  getParentRoute: () => navRouteRoute,
} as any)
const navMembersIndexRoute = navMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => navRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const navMusicSlugRouteRoute = navMusicSlugRouteRouteImport.update({
  id: '/music/$slug',
  path: '/music/$slug',
  getParentRoute: () => navRouteRoute,
} as any)
const navMusicSlugIndexRoute = navMusicSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => navMusicSlugRouteRoute,
} as any)
const navAdminPostsIndexRoute = navAdminPostsIndexRouteImport.update({
  id: '/admin/posts/',
  path: '/admin/posts/',
  getParentRoute: () => navRouteRoute,
} as any)
const navMusicSlugTrackRoute = navMusicSlugTrackRouteImport.update({
  id: '/$track',
  path: '/$track',
  getParentRoute: () => navMusicSlugRouteRoute,
} as any)
const navMembersPostSlugRoute = navMembersPostSlugRouteImport.update({
  id: '/members/post/$slug',
  path: '/members/post/$slug',
  getParentRoute: () => navRouteRoute,
} as any)
const navAdminPostsNewRoute = navAdminPostsNewRouteImport.update({
  id: '/admin/posts/new',
  path: '/admin/posts/new',
  getParentRoute: () => navRouteRoute,
} as any)
const navAdminPostsPostIdRoute = navAdminPostsPostIdRouteImport.update({
  id: '/admin/posts/$postId',
  path: '/admin/posts/$postId',
  getParentRoute: () => navRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRoute
  '/links': typeof LinksRoute
  '/contact': typeof navContactRoute
  '/login': typeof navLoginRoute
  '/tour': typeof navTourRoute
  '/videos': typeof navVideosRoute
  '/work-with-me': typeof navWorkWithMeRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof navIndexRoute
  '/music/$slug': typeof navMusicSlugRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/members': typeof navMembersIndexRoute
  '/music': typeof navMusicIndexRoute
  '/admin/posts/$postId': typeof navAdminPostsPostIdRoute
  '/admin/posts/new': typeof navAdminPostsNewRoute
  '/members/post/$slug': typeof navMembersPostSlugRoute
  '/music/$slug/$track': typeof navMusicSlugTrackRoute
  '/admin/posts': typeof navAdminPostsIndexRoute
  '/music/$slug/': typeof navMusicSlugIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRoute
  '/links': typeof LinksRoute
  '/contact': typeof navContactRoute
  '/login': typeof navLoginRoute
  '/tour': typeof navTourRoute
  '/videos': typeof navVideosRoute
  '/work-with-me': typeof navWorkWithMeRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof navIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/members': typeof navMembersIndexRoute
  '/music': typeof navMusicIndexRoute
  '/admin/posts/$postId': typeof navAdminPostsPostIdRoute
  '/admin/posts/new': typeof navAdminPostsNewRoute
  '/members/post/$slug': typeof navMembersPostSlugRoute
  '/music/$slug/$track': typeof navMusicSlugTrackRoute
  '/admin/posts': typeof navAdminPostsIndexRoute
  '/music/$slug': typeof navMusicSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(nav)': typeof navRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/links': typeof LinksRoute
  '/(nav)/contact': typeof navContactRoute
  '/(nav)/login': typeof navLoginRoute
  '/(nav)/tour': typeof navTourRoute
  '/(nav)/videos': typeof navVideosRoute
  '/(nav)/work-with-me': typeof navWorkWithMeRoute
  '/api/health': typeof ApiHealthRoute
  '/(nav)/': typeof navIndexRoute
  '/(nav)/music/$slug': typeof navMusicSlugRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(nav)/members/': typeof navMembersIndexRoute
  '/(nav)/music/': typeof navMusicIndexRoute
  '/(nav)/admin/posts/$postId': typeof navAdminPostsPostIdRoute
  '/(nav)/admin/posts/new': typeof navAdminPostsNewRoute
  '/(nav)/members/post/$slug': typeof navMembersPostSlugRoute
  '/(nav)/music/$slug/$track': typeof navMusicSlugTrackRoute
  '/(nav)/admin/posts/': typeof navAdminPostsIndexRoute
  '/(nav)/music/$slug/': typeof navMusicSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/links'
    | '/contact'
    | '/login'
    | '/tour'
    | '/videos'
    | '/work-with-me'
    | '/api/health'
    | '/'
    | '/music/$slug'
    | '/api/auth/$'
    | '/members'
    | '/music'
    | '/admin/posts/$postId'
    | '/admin/posts/new'
    | '/members/post/$slug'
    | '/music/$slug/$track'
    | '/admin/posts'
    | '/music/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/links'
    | '/contact'
    | '/login'
    | '/tour'
    | '/videos'
    | '/work-with-me'
    | '/api/health'
    | '/'
    | '/api/auth/$'
    | '/members'
    | '/music'
    | '/admin/posts/$postId'
    | '/admin/posts/new'
    | '/members/post/$slug'
    | '/music/$slug/$track'
    | '/admin/posts'
    | '/music/$slug'
  id:
    | '__root__'
    | '/(nav)'
    | '/dashboard'
    | '/links'
    | '/(nav)/contact'
    | '/(nav)/login'
    | '/(nav)/tour'
    | '/(nav)/videos'
    | '/(nav)/work-with-me'
    | '/api/health'
    | '/(nav)/'
    | '/(nav)/music/$slug'
    | '/api/auth/$'
    | '/(nav)/members/'
    | '/(nav)/music/'
    | '/(nav)/admin/posts/$postId'
    | '/(nav)/admin/posts/new'
    | '/(nav)/members/post/$slug'
    | '/(nav)/music/$slug/$track'
    | '/(nav)/admin/posts/'
    | '/(nav)/music/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  navRouteRoute: typeof navRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LinksRoute: typeof LinksRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(nav)': {
      id: '/(nav)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof navRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(nav)/': {
      id: '/(nav)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof navIndexRouteImport
      parentRoute: typeof navRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(nav)/work-with-me': {
      id: '/(nav)/work-with-me'
      path: '/work-with-me'
      fullPath: '/work-with-me'
      preLoaderRoute: typeof navWorkWithMeRouteImport
      parentRoute: typeof navRouteRoute
    }
    '/(nav)/videos': {
      id: '/(nav)/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof navVideosRouteImport
      parentRoute: typeof navRouteRoute
    }
    '/(nav)/tour': {
      id: '/(nav)/tour'
      path: '/tour'
      fullPath: '/tour'
      preLoaderRoute: typeof navTourRouteImport
      parentRoute: typeof navRouteRoute
    }
    '/(nav)/login': {
      id: '/(nav)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof navLoginRouteImport
      parentRoute: typeof navRouteRoute
    }
    '/(nav)/contact': {
      id: '/(nav)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof navContactRouteImport
      parentRoute: typeof navRouteRoute
    }
    '/(nav)/music/': {
      id: '/(nav)/music/'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof navMusicIndexRouteImport
      parentRoute: typeof navRouteRoute
    }
    '/(nav)/members/': {
      id: '/(nav)/members/'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof navMembersIndexRouteImport
      parentRoute: typeof navRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(nav)/music/$slug': {
      id: '/(nav)/music/$slug'
      path: '/music/$slug'
      fullPath: '/music/$slug'
      preLoaderRoute: typeof navMusicSlugRouteRouteImport
      parentRoute: typeof navRouteRoute
    }
    '/(nav)/music/$slug/': {
      id: '/(nav)/music/$slug/'
      path: '/'
      fullPath: '/music/$slug/'
      preLoaderRoute: typeof navMusicSlugIndexRouteImport
      parentRoute: typeof navMusicSlugRouteRoute
    }
    '/(nav)/admin/posts/': {
      id: '/(nav)/admin/posts/'
      path: '/admin/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof navAdminPostsIndexRouteImport
      parentRoute: typeof navRouteRoute
    }
    '/(nav)/music/$slug/$track': {
      id: '/(nav)/music/$slug/$track'
      path: '/$track'
      fullPath: '/music/$slug/$track'
      preLoaderRoute: typeof navMusicSlugTrackRouteImport
      parentRoute: typeof navMusicSlugRouteRoute
    }
    '/(nav)/members/post/$slug': {
      id: '/(nav)/members/post/$slug'
      path: '/members/post/$slug'
      fullPath: '/members/post/$slug'
      preLoaderRoute: typeof navMembersPostSlugRouteImport
      parentRoute: typeof navRouteRoute
    }
    '/(nav)/admin/posts/new': {
      id: '/(nav)/admin/posts/new'
      path: '/admin/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof navAdminPostsNewRouteImport
      parentRoute: typeof navRouteRoute
    }
    '/(nav)/admin/posts/$postId': {
      id: '/(nav)/admin/posts/$postId'
      path: '/admin/posts/$postId'
      fullPath: '/admin/posts/$postId'
      preLoaderRoute: typeof navAdminPostsPostIdRouteImport
      parentRoute: typeof navRouteRoute
    }
  }
}

interface navMusicSlugRouteRouteChildren {
  navMusicSlugTrackRoute: typeof navMusicSlugTrackRoute
  navMusicSlugIndexRoute: typeof navMusicSlugIndexRoute
}

const navMusicSlugRouteRouteChildren: navMusicSlugRouteRouteChildren = {
  navMusicSlugTrackRoute: navMusicSlugTrackRoute,
  navMusicSlugIndexRoute: navMusicSlugIndexRoute,
}

const navMusicSlugRouteRouteWithChildren =
  navMusicSlugRouteRoute._addFileChildren(navMusicSlugRouteRouteChildren)

interface navRouteRouteChildren {
  navContactRoute: typeof navContactRoute
  navLoginRoute: typeof navLoginRoute
  navTourRoute: typeof navTourRoute
  navVideosRoute: typeof navVideosRoute
  navWorkWithMeRoute: typeof navWorkWithMeRoute
  navIndexRoute: typeof navIndexRoute
  navMusicSlugRouteRoute: typeof navMusicSlugRouteRouteWithChildren
  navMembersIndexRoute: typeof navMembersIndexRoute
  navMusicIndexRoute: typeof navMusicIndexRoute
  navAdminPostsPostIdRoute: typeof navAdminPostsPostIdRoute
  navAdminPostsNewRoute: typeof navAdminPostsNewRoute
  navMembersPostSlugRoute: typeof navMembersPostSlugRoute
  navAdminPostsIndexRoute: typeof navAdminPostsIndexRoute
}

const navRouteRouteChildren: navRouteRouteChildren = {
  navContactRoute: navContactRoute,
  navLoginRoute: navLoginRoute,
  navTourRoute: navTourRoute,
  navVideosRoute: navVideosRoute,
  navWorkWithMeRoute: navWorkWithMeRoute,
  navIndexRoute: navIndexRoute,
  navMusicSlugRouteRoute: navMusicSlugRouteRouteWithChildren,
  navMembersIndexRoute: navMembersIndexRoute,
  navMusicIndexRoute: navMusicIndexRoute,
  navAdminPostsPostIdRoute: navAdminPostsPostIdRoute,
  navAdminPostsNewRoute: navAdminPostsNewRoute,
  navMembersPostSlugRoute: navMembersPostSlugRoute,
  navAdminPostsIndexRoute: navAdminPostsIndexRoute,
}

const navRouteRouteWithChildren = navRouteRoute._addFileChildren(
  navRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  navRouteRoute: navRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LinksRoute: LinksRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
