/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LinksRouteImport } from './routes/links'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as TestRouteRouteImport } from './routes/test/route'
import { Route as navRouteRouteImport } from './routes/(nav)/route'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as navIndexRouteImport } from './routes/(nav)/index'
import { Route as navVideosRouteImport } from './routes/(nav)/videos'
import { Route as navTourRouteImport } from './routes/(nav)/tour'
import { Route as navProductionRouteImport } from './routes/(nav)/production'
import { Route as navLoginRouteImport } from './routes/(nav)/login'
import { Route as navContactRouteImport } from './routes/(nav)/contact'
import { Route as navMusicIndexRouteImport } from './routes/(nav)/music/index'
import { Route as navBlogIndexRouteImport } from './routes/(nav)/blog/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as navMusicReleaseIdRouteImport } from './routes/(nav)/music/$releaseId'
import { Route as navBlogSlugRouteImport } from './routes/(nav)/blog/$slug'

const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRouteRoute = TestRouteRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const navRouteRoute = navRouteRouteImport.update({
  id: '/(nav)',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestRouteRoute,
} as any)
const navIndexRoute = navIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => navRouteRoute,
} as any)
const navVideosRoute = navVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => navRouteRoute,
} as any)
const navTourRoute = navTourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => navRouteRoute,
} as any)
const navProductionRoute = navProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => navRouteRoute,
} as any)
const navLoginRoute = navLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => navRouteRoute,
} as any)
const navContactRoute = navContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => navRouteRoute,
} as any)
const navMusicIndexRoute = navMusicIndexRouteImport.update({
  id: '/music/',
  path: '/music/',
  getParentRoute: () => navRouteRoute,
} as any)
const navBlogIndexRoute = navBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => navRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const navMusicReleaseIdRoute = navMusicReleaseIdRouteImport.update({
  id: '/music/$releaseId',
  path: '/music/$releaseId',
  getParentRoute: () => navRouteRoute,
} as any)
const navBlogSlugRoute = navBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => navRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/test': typeof TestRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/links': typeof LinksRoute
  '/contact': typeof navContactRoute
  '/login': typeof navLoginRoute
  '/production': typeof navProductionRoute
  '/tour': typeof navTourRoute
  '/videos': typeof navVideosRoute
  '/': typeof navIndexRoute
  '/test/': typeof TestIndexRoute
  '/blog/$slug': typeof navBlogSlugRoute
  '/music/$releaseId': typeof navMusicReleaseIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/blog': typeof navBlogIndexRoute
  '/music': typeof navMusicIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRoute
  '/links': typeof LinksRoute
  '/contact': typeof navContactRoute
  '/login': typeof navLoginRoute
  '/production': typeof navProductionRoute
  '/tour': typeof navTourRoute
  '/videos': typeof navVideosRoute
  '/': typeof navIndexRoute
  '/test': typeof TestIndexRoute
  '/blog/$slug': typeof navBlogSlugRoute
  '/music/$releaseId': typeof navMusicReleaseIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/blog': typeof navBlogIndexRoute
  '/music': typeof navMusicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(nav)': typeof navRouteRouteWithChildren
  '/test': typeof TestRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/links': typeof LinksRoute
  '/(nav)/contact': typeof navContactRoute
  '/(nav)/login': typeof navLoginRoute
  '/(nav)/production': typeof navProductionRoute
  '/(nav)/tour': typeof navTourRoute
  '/(nav)/videos': typeof navVideosRoute
  '/(nav)/': typeof navIndexRoute
  '/test/': typeof TestIndexRoute
  '/(nav)/blog/$slug': typeof navBlogSlugRoute
  '/(nav)/music/$releaseId': typeof navMusicReleaseIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(nav)/blog/': typeof navBlogIndexRoute
  '/(nav)/music/': typeof navMusicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/test'
    | '/dashboard'
    | '/links'
    | '/contact'
    | '/login'
    | '/production'
    | '/tour'
    | '/videos'
    | '/'
    | '/test/'
    | '/blog/$slug'
    | '/music/$releaseId'
    | '/api/auth/$'
    | '/blog'
    | '/music'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/links'
    | '/contact'
    | '/login'
    | '/production'
    | '/tour'
    | '/videos'
    | '/'
    | '/test'
    | '/blog/$slug'
    | '/music/$releaseId'
    | '/api/auth/$'
    | '/blog'
    | '/music'
  id:
    | '__root__'
    | '/(nav)'
    | '/test'
    | '/dashboard'
    | '/links'
    | '/(nav)/contact'
    | '/(nav)/login'
    | '/(nav)/production'
    | '/(nav)/tour'
    | '/(nav)/videos'
    | '/(nav)/'
    | '/test/'
    | '/(nav)/blog/$slug'
    | '/(nav)/music/$releaseId'
    | '/api/auth/$'
    | '/(nav)/blog/'
    | '/(nav)/music/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  navRouteRoute: typeof navRouteRouteWithChildren
  TestRouteRoute: typeof TestRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LinksRoute: typeof LinksRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(nav)': {
      id: '/(nav)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof navRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof TestRouteRoute
    }
    '/(nav)/': {
      id: '/(nav)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof navIndexRouteImport
      parentRoute: typeof navRouteRoute
    }
    '/(nav)/videos': {
      id: '/(nav)/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof navVideosRouteImport
      parentRoute: typeof navRouteRoute
    }
    '/(nav)/tour': {
      id: '/(nav)/tour'
      path: '/tour'
      fullPath: '/tour'
      preLoaderRoute: typeof navTourRouteImport
      parentRoute: typeof navRouteRoute
    }
    '/(nav)/production': {
      id: '/(nav)/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof navProductionRouteImport
      parentRoute: typeof navRouteRoute
    }
    '/(nav)/login': {
      id: '/(nav)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof navLoginRouteImport
      parentRoute: typeof navRouteRoute
    }
    '/(nav)/contact': {
      id: '/(nav)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof navContactRouteImport
      parentRoute: typeof navRouteRoute
    }
    '/(nav)/music/': {
      id: '/(nav)/music/'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof navMusicIndexRouteImport
      parentRoute: typeof navRouteRoute
    }
    '/(nav)/blog/': {
      id: '/(nav)/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof navBlogIndexRouteImport
      parentRoute: typeof navRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(nav)/music/$releaseId': {
      id: '/(nav)/music/$releaseId'
      path: '/music/$releaseId'
      fullPath: '/music/$releaseId'
      preLoaderRoute: typeof navMusicReleaseIdRouteImport
      parentRoute: typeof navRouteRoute
    }
    '/(nav)/blog/$slug': {
      id: '/(nav)/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof navBlogSlugRouteImport
      parentRoute: typeof navRouteRoute
    }
  }
}

interface navRouteRouteChildren {
  navContactRoute: typeof navContactRoute
  navLoginRoute: typeof navLoginRoute
  navProductionRoute: typeof navProductionRoute
  navTourRoute: typeof navTourRoute
  navVideosRoute: typeof navVideosRoute
  navIndexRoute: typeof navIndexRoute
  navBlogSlugRoute: typeof navBlogSlugRoute
  navMusicReleaseIdRoute: typeof navMusicReleaseIdRoute
  navBlogIndexRoute: typeof navBlogIndexRoute
  navMusicIndexRoute: typeof navMusicIndexRoute
}

const navRouteRouteChildren: navRouteRouteChildren = {
  navContactRoute: navContactRoute,
  navLoginRoute: navLoginRoute,
  navProductionRoute: navProductionRoute,
  navTourRoute: navTourRoute,
  navVideosRoute: navVideosRoute,
  navIndexRoute: navIndexRoute,
  navBlogSlugRoute: navBlogSlugRoute,
  navMusicReleaseIdRoute: navMusicReleaseIdRoute,
  navBlogIndexRoute: navBlogIndexRoute,
  navMusicIndexRoute: navMusicIndexRoute,
}

const navRouteRouteWithChildren = navRouteRoute._addFileChildren(
  navRouteRouteChildren,
)

interface TestRouteRouteChildren {
  TestIndexRoute: typeof TestIndexRoute
}

const TestRouteRouteChildren: TestRouteRouteChildren = {
  TestIndexRoute: TestIndexRoute,
}

const TestRouteRouteWithChildren = TestRouteRoute._addFileChildren(
  TestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  navRouteRoute: navRouteRouteWithChildren,
  TestRouteRoute: TestRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LinksRoute: LinksRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
