import type { ApiReleaseDetails } from "./music-types";

// Seed data used when cache is empty and API is unavailable
// This ensures the app works even without API configuration
export const musicSeedData: ApiReleaseDetails[] = [
  {
    id: 2234234,
    title: "Latest Single",
    artist: "Luke Roes",
    type: "Single",
    releaseDate: "2024-01-01",
    upc: "000000000001",
    catalogNumber: "LR-001",
    status: "Live",
    artworkFileKey: "https://placehold.co/400x400/1a1a1a/white?text=Single",
    streamingLinks: {
      spotify: "https://open.spotify.com",
      appleMusic: "https://music.apple.com",
      youtube: "https://youtube.com",
      soundcloud: null,
      bandcamp: null,
    },
    distributor: null,
    distributionDate: null,
    releaseLabel: null,
    version: null,
    countriesOfFirstRelease: [],
    copyrightOwnerCountryOfNationality: null,
    tracks: [
      {
        id: "1-track-1",
        trackNumber: 1,
        title: "Latest Single",
        artist: "Luke Roes",
        duration: "3:45",
        isrc: "US-TEST-00001",
        lyrics: "Sample lyrics for the latest single.",
      },
    ],
  },
  {
    id: 3453452,
    title: "Debut Album",
    artist: "Luke Roes",
    type: "Album",
    releaseDate: "2023-01-01",
    upc: "000000000002",
    catalogNumber: "LR-002",
    status: "Live",
    artworkFileKey: "https://placehold.co/400x400/2a2a2a/white?text=Album",
    streamingLinks: {
      spotify: "https://open.spotify.com",
      appleMusic: "https://music.apple.com",
      youtube: null,
      soundcloud: null,
      bandcamp: null,
    },
    distributor: null,
    distributionDate: null,
    releaseLabel: null,
    version: null,
    countriesOfFirstRelease: [],
    copyrightOwnerCountryOfNationality: null,
    tracks: [
      {
        id: "2-track-1",
        trackNumber: 1,
        title: "Opening Track",
        duration: "4:12",
        artist: "Luke Roes",
        isrc: null,
      },
      {
        id: "2-track-2",
        trackNumber: 2,
        title: "Second Song",
        duration: "3:58",
        artist: "Luke Roes",
        isrc: null,
      },
      {
        id: "2-track-3",
        trackNumber: 3,
        title: "Interlude",
        duration: "1:30",
        artist: "Luke Roes",
        isrc: null,
      },
      {
        id: "2-track-4",
        trackNumber: 4,
        title: "Best Track",
        duration: "4:45",
        artist: "Luke Roes",
        isrc: null,
      },
      {
        id: "2-track-5",
        trackNumber: 5,
        title: "Slow Jam",
        duration: "5:20",
        artist: "Luke Roes",
        isrc: null,
      },
      {
        id: "2-track-6",
        trackNumber: 6,
        title: "Upbeat Anthem",
        duration: "3:15",
        artist: "Luke Roes",
        isrc: null,
      },
      {
        id: "2-track-7",
        trackNumber: 7,
        title: "Emotional Ballad",
        duration: "4:30",
        artist: "Luke Roes",
        isrc: null,
      },
      {
        id: "2-track-8",
        trackNumber: 8,
        title: "Closing Song",
        duration: "4:05",
        artist: "Luke Roes",
        isrc: null,
      },
    ],
  },
  {
    id: 433,
    title: "Summer EP",
    artist: "Luke Roes",
    type: "EP",
    releaseDate: "2023-06-01",
    upc: "000000000003",
    catalogNumber: "LR-003",
    status: "Live",
    artworkFileKey: "https://placehold.co/400x400/3a3a3a/white?text=EP",
    streamingLinks: {
      spotify: null,
      appleMusic: null,
      youtube: "https://youtube.com",
      soundcloud: null,
      bandcamp: null,
    },
    distributor: null,
    distributionDate: null,
    releaseLabel: null,
    version: null,
    countriesOfFirstRelease: [],
    copyrightOwnerCountryOfNationality: null,
    tracks: [
      {
        id: "3-track-1",
        trackNumber: 1,
        title: "Summer Vibes",
        duration: "3:22",
        artist: "Luke Roes",
        isrc: null,
      },
      {
        id: "3-track-2",
        trackNumber: 2,
        title: "Beach Day",
        duration: "3:48",
        artist: "Luke Roes",
        isrc: null,
      },
      {
        id: "3-track-3",
        trackNumber: 3,
        title: "Sunset Drive",
        duration: "4:15",
        artist: "Luke Roes",
        isrc: null,
      },
      {
        id: "3-track-4",
        trackNumber: 4,
        title: "Late Night",
        duration: "3:55",
        artist: "Luke Roes",
        isrc: null,
      },
    ],
  },
  {
    id: 43345345,
    title: "Previous Single",
    artist: "Luke Roes",
    type: "Single",
    releaseDate: "2022-03-01",
    upc: "000000000004",
    catalogNumber: "LR-004",
    status: "Live",
    artworkFileKey: "https://placehold.co/400x400/4a4a4a/white?text=Single",
    streamingLinks: {
      spotify: null,
      appleMusic: null,
      youtube: null,
      soundcloud: null,
      bandcamp: null,
    },
    distributor: null,
    distributionDate: null,
    releaseLabel: null,
    version: null,
    countriesOfFirstRelease: [],
    copyrightOwnerCountryOfNationality: null,
    tracks: [
      {
        id: "4-track-1",
        trackNumber: 1,
        title: "Previous Single",
        duration: "3:30",
        artist: "Luke Roes",
        isrc: null,
      },
    ],
  },
  {
    id: 54353,
    title: "Acoustic Sessions",
    artist: "Luke Roes",
    type: "EP",
    releaseDate: "2022-08-01",
    upc: "000000000005",
    catalogNumber: "LR-005",
    status: "Live",
    artworkFileKey: "https://placehold.co/400x400/5a5a5a/white?text=EP",
    streamingLinks: {
      spotify: "https://open.spotify.com",
      appleMusic: null,
      youtube: null,
      soundcloud: null,
      bandcamp: null,
    },
    distributor: null,
    distributionDate: null,
    releaseLabel: null,
    version: null,
    countriesOfFirstRelease: [],
    copyrightOwnerCountryOfNationality: null,
    tracks: [
      {
        id: "5-track-1",
        trackNumber: 1,
        title: "Unplugged Version",
        duration: "4:05",
        artist: "Luke Roes",
        isrc: null,
      },
      {
        id: "5-track-2",
        trackNumber: 2,
        title: "Stripped Down",
        duration: "3:40",
        artist: "Luke Roes",
        isrc: null,
      },
      {
        id: "5-track-3",
        trackNumber: 3,
        title: "Raw Emotion",
        duration: "4:25",
        artist: "Luke Roes",
        isrc: null,
      },
    ],
  },
];
