import type { ApiReleaseDetails } from "./music-types";

// Seed data used when cache is empty and API is unavailable
// This ensures the app works even without API configuration
export const musicSeedData: ApiReleaseDetails[] = [
  {
    id: 2234234,
    title: "Latest Single",
    artist: "Luke Roes",
    type: "Single",
    releaseDate: "2024-01-01",
    upc: "000000000001",
    catalogNumber: "LR-001",
    status: "Live",
    artworkFileKey: "https://placehold.co/400x400/1a1a1a/white?text=Single",
    artworkPublicUrl: "https://placehold.co/400x400/1a1a1a/white?text=Single",
    streamingLinks: {
      spotify: "https://open.spotify.com",
      appleMusic: "https://music.apple.com",
      youtube: "https://youtube.com",
      soundcloud: null,
      bandcamp: null,
    },
    distributor: null,
    distributionDate: null,
    releaseLabel: null,
    version: null,
    countriesOfFirstRelease: [],
    copyrightOwnerCountryOfNationality: null,
    tracks: [
      {
        id: 1001,
        trackNumber: 1,
        title: "Latest Single",
        artist: "Luke Roes",
        duration: null,
        isrc: "US-TEST-00001",
        lyrics: "Sample lyrics for the latest single.",
        song: {
          id: 2001,
          title: "Latest Single",
          lyrics: "Sample lyrics for the latest single.",
          songwriters: null,
          iswc: null,
          genre: null,
          workType: null,
          language: null,
          copyrightYear: null,
          isInstrumental: false,
        },
        recording: {
          versionId: null,
          versionTitle: null,
          bpm: null,
          keySignature: null,
          timeSignature: null,
          studio: null,
          recordingDate: null,
          dateOfFirstRelease: null,
          countryOfMastering: null,
          countryOfRecording: null,
          primaryGenre: null,
          secondaryGenre: null,
          hasExplicitLyrics: null,
          labelName: null,
          credits: null,
          masterOwners: null,
          nonFeaturedPerformers: null,
        },
      },
    ],
  },
  {
    id: 3453452,
    title: "Debut Album",
    artist: "Luke Roes",
    type: "Album",
    releaseDate: "2023-01-01",
    upc: "000000000002",
    catalogNumber: "LR-002",
    status: "Live",
    artworkFileKey: "https://placehold.co/400x400/2a2a2a/white?text=Album",
    artworkPublicUrl: "https://placehold.co/400x400/2a2a2a/white?text=Album",
    streamingLinks: {
      spotify: "https://open.spotify.com",
      appleMusic: "https://music.apple.com",
      youtube: null,
      soundcloud: null,
      bandcamp: null,
    },
    distributor: null,
    distributionDate: null,
    releaseLabel: null,
    version: null,
    countriesOfFirstRelease: [],
    copyrightOwnerCountryOfNationality: null,
    tracks: [
      {
        id: 2001,
        trackNumber: 1,
        title: "Opening Track",
        duration: null,
        artist: "Luke Roes",
        isrc: null,
        song: {
          id: 3001,
          title: "Opening Track",
          lyrics: null,
          songwriters: null,
          iswc: null,
          genre: null,
          workType: null,
          language: null,
          copyrightYear: null,
          isInstrumental: null,
        },
        recording: {
          versionId: null,
          versionTitle: null,
          bpm: null,
          keySignature: null,
          timeSignature: null,
          studio: null,
          recordingDate: null,
          dateOfFirstRelease: null,
          countryOfMastering: null,
          countryOfRecording: null,
          primaryGenre: null,
          secondaryGenre: null,
          hasExplicitLyrics: null,
          labelName: null,
          credits: null,
          masterOwners: null,
          nonFeaturedPerformers: null,
        },
      },
      {
        id: 2002,
        trackNumber: 2,
        title: "Second Song",
        duration: null,
        artist: "Luke Roes",
        isrc: null,
        song: {
          id: 3002,
          title: "Second Song",
          lyrics: null,
          songwriters: null,
          iswc: null,
          genre: null,
          workType: null,
          language: null,
          copyrightYear: null,
          isInstrumental: null,
        },
        recording: {
          versionId: null,
          versionTitle: null,
          bpm: null,
          keySignature: null,
          timeSignature: null,
          studio: null,
          recordingDate: null,
          dateOfFirstRelease: null,
          countryOfMastering: null,
          countryOfRecording: null,
          primaryGenre: null,
          secondaryGenre: null,
          hasExplicitLyrics: null,
          labelName: null,
          credits: null,
          masterOwners: null,
          nonFeaturedPerformers: null,
        },
      },
      {
        id: 2003,
        trackNumber: 3,
        title: "Interlude",
        duration: null,
        artist: "Luke Roes",
        isrc: null,
        song: {
          id: 3003,
          title: "Interlude",
          lyrics: null,
          songwriters: null,
          iswc: null,
          genre: null,
          workType: null,
          language: null,
          copyrightYear: null,
          isInstrumental: null,
        },
        recording: {
          versionId: null,
          versionTitle: null,
          bpm: null,
          keySignature: null,
          timeSignature: null,
          studio: null,
          recordingDate: null,
          dateOfFirstRelease: null,
          countryOfMastering: null,
          countryOfRecording: null,
          primaryGenre: null,
          secondaryGenre: null,
          hasExplicitLyrics: null,
          labelName: null,
          credits: null,
          masterOwners: null,
          nonFeaturedPerformers: null,
        },
      },
      {
        id: 2004,
        trackNumber: 4,
        title: "Best Track",
        duration: null,
        artist: "Luke Roes",
        isrc: null,
        song: {
          id: 3004,
          title: "Best Track",
          lyrics: null,
          songwriters: null,
          iswc: null,
          genre: null,
          workType: null,
          language: null,
          copyrightYear: null,
          isInstrumental: null,
        },
        recording: {
          versionId: null,
          versionTitle: null,
          bpm: null,
          keySignature: null,
          timeSignature: null,
          studio: null,
          recordingDate: null,
          dateOfFirstRelease: null,
          countryOfMastering: null,
          countryOfRecording: null,
          primaryGenre: null,
          secondaryGenre: null,
          hasExplicitLyrics: null,
          labelName: null,
          credits: null,
          masterOwners: null,
          nonFeaturedPerformers: null,
        },
      },
      {
        id: 2005,
        trackNumber: 5,
        title: "Slow Jam",
        duration: null,
        artist: "Luke Roes",
        isrc: null,
        song: {
          id: 3005,
          title: "Slow Jam",
          lyrics: null,
          songwriters: null,
          iswc: null,
          genre: null,
          workType: null,
          language: null,
          copyrightYear: null,
          isInstrumental: null,
        },
        recording: {
          versionId: null,
          versionTitle: null,
          bpm: null,
          keySignature: null,
          timeSignature: null,
          studio: null,
          recordingDate: null,
          dateOfFirstRelease: null,
          countryOfMastering: null,
          countryOfRecording: null,
          primaryGenre: null,
          secondaryGenre: null,
          hasExplicitLyrics: null,
          labelName: null,
          credits: null,
          masterOwners: null,
          nonFeaturedPerformers: null,
        },
      },
      {
        id: 2006,
        trackNumber: 6,
        title: "Upbeat Anthem",
        duration: null,
        artist: "Luke Roes",
        isrc: null,
        song: {
          id: 3006,
          title: "Upbeat Anthem",
          lyrics: null,
          songwriters: null,
          iswc: null,
          genre: null,
          workType: null,
          language: null,
          copyrightYear: null,
          isInstrumental: null,
        },
        recording: {
          versionId: null,
          versionTitle: null,
          bpm: null,
          keySignature: null,
          timeSignature: null,
          studio: null,
          recordingDate: null,
          dateOfFirstRelease: null,
          countryOfMastering: null,
          countryOfRecording: null,
          primaryGenre: null,
          secondaryGenre: null,
          hasExplicitLyrics: null,
          labelName: null,
          credits: null,
          masterOwners: null,
          nonFeaturedPerformers: null,
        },
      },
      {
        id: 2007,
        trackNumber: 7,
        title: "Emotional Ballad",
        duration: null,
        artist: "Luke Roes",
        isrc: null,
        song: {
          id: 3007,
          title: "Emotional Ballad",
          lyrics: null,
          songwriters: null,
          iswc: null,
          genre: null,
          workType: null,
          language: null,
          copyrightYear: null,
          isInstrumental: null,
        },
        recording: {
          versionId: null,
          versionTitle: null,
          bpm: null,
          keySignature: null,
          timeSignature: null,
          studio: null,
          recordingDate: null,
          dateOfFirstRelease: null,
          countryOfMastering: null,
          countryOfRecording: null,
          primaryGenre: null,
          secondaryGenre: null,
          hasExplicitLyrics: null,
          labelName: null,
          credits: null,
          masterOwners: null,
          nonFeaturedPerformers: null,
        },
      },
      {
        id: 2008,
        trackNumber: 8,
        title: "Closing Song",
        duration: null,
        artist: "Luke Roes",
        isrc: null,
        song: {
          id: 3008,
          title: "Closing Song",
          lyrics: null,
          songwriters: null,
          iswc: null,
          genre: null,
          workType: null,
          language: null,
          copyrightYear: null,
          isInstrumental: null,
        },
        recording: {
          versionId: null,
          versionTitle: null,
          bpm: null,
          keySignature: null,
          timeSignature: null,
          studio: null,
          recordingDate: null,
          dateOfFirstRelease: null,
          countryOfMastering: null,
          countryOfRecording: null,
          primaryGenre: null,
          secondaryGenre: null,
          hasExplicitLyrics: null,
          labelName: null,
          credits: null,
          masterOwners: null,
          nonFeaturedPerformers: null,
        },
      },
    ],
  },
  {
    id: 433,
    title: "Summer EP",
    artist: "Luke Roes",
    type: "EP",
    releaseDate: "2023-06-01",
    upc: "000000000003",
    catalogNumber: "LR-003",
    status: "Live",
    artworkFileKey: "https://placehold.co/400x400/3a3a3a/white?text=EP",
    artworkPublicUrl: "https://placehold.co/400x400/3a3a3a/white?text=EP",
    streamingLinks: {
      spotify: null,
      appleMusic: null,
      youtube: "https://youtube.com",
      soundcloud: null,
      bandcamp: null,
    },
    distributor: null,
    distributionDate: null,
    releaseLabel: null,
    version: null,
    countriesOfFirstRelease: [],
    copyrightOwnerCountryOfNationality: null,
    tracks: [
      {
        id: 3001,
        trackNumber: 1,
        title: "Summer Vibes",
        duration: null,
        artist: "Luke Roes",
        isrc: null,
        song: {
          id: 4001,
          title: "Summer Vibes",
          lyrics: null,
          songwriters: null,
          iswc: null,
          genre: null,
          workType: null,
          language: null,
          copyrightYear: null,
          isInstrumental: null,
        },
        recording: {
          versionId: null,
          versionTitle: null,
          bpm: null,
          keySignature: null,
          timeSignature: null,
          studio: null,
          recordingDate: null,
          dateOfFirstRelease: null,
          countryOfMastering: null,
          countryOfRecording: null,
          primaryGenre: null,
          secondaryGenre: null,
          hasExplicitLyrics: null,
          labelName: null,
          credits: null,
          masterOwners: null,
          nonFeaturedPerformers: null,
        },
      },
      {
        id: 3002,
        trackNumber: 2,
        title: "Beach Day",
        duration: null,
        artist: "Luke Roes",
        isrc: null,
        song: {
          id: 4002,
          title: "Beach Day",
          lyrics: null,
          songwriters: null,
          iswc: null,
          genre: null,
          workType: null,
          language: null,
          copyrightYear: null,
          isInstrumental: null,
        },
        recording: {
          versionId: null,
          versionTitle: null,
          bpm: null,
          keySignature: null,
          timeSignature: null,
          studio: null,
          recordingDate: null,
          dateOfFirstRelease: null,
          countryOfMastering: null,
          countryOfRecording: null,
          primaryGenre: null,
          secondaryGenre: null,
          hasExplicitLyrics: null,
          labelName: null,
          credits: null,
          masterOwners: null,
          nonFeaturedPerformers: null,
        },
      },
      {
        id: 3003,
        trackNumber: 3,
        title: "Sunset Drive",
        duration: null,
        artist: "Luke Roes",
        isrc: null,
        song: {
          id: 4003,
          title: "Sunset Drive",
          lyrics: null,
          songwriters: null,
          iswc: null,
          genre: null,
          workType: null,
          language: null,
          copyrightYear: null,
          isInstrumental: null,
        },
        recording: {
          versionId: null,
          versionTitle: null,
          bpm: null,
          keySignature: null,
          timeSignature: null,
          studio: null,
          recordingDate: null,
          dateOfFirstRelease: null,
          countryOfMastering: null,
          countryOfRecording: null,
          primaryGenre: null,
          secondaryGenre: null,
          hasExplicitLyrics: null,
          labelName: null,
          credits: null,
          masterOwners: null,
          nonFeaturedPerformers: null,
        },
      },
      {
        id: 3004,
        trackNumber: 4,
        title: "Late Night",
        duration: null,
        artist: "Luke Roes",
        isrc: null,
        song: {
          id: 4004,
          title: "Late Night",
          lyrics: null,
          songwriters: null,
          iswc: null,
          genre: null,
          workType: null,
          language: null,
          copyrightYear: null,
          isInstrumental: null,
        },
        recording: {
          versionId: null,
          versionTitle: null,
          bpm: null,
          keySignature: null,
          timeSignature: null,
          studio: null,
          recordingDate: null,
          dateOfFirstRelease: null,
          countryOfMastering: null,
          countryOfRecording: null,
          primaryGenre: null,
          secondaryGenre: null,
          hasExplicitLyrics: null,
          labelName: null,
          credits: null,
          masterOwners: null,
          nonFeaturedPerformers: null,
        },
      },
    ],
  },
  {
    id: 43345345,
    title: "Previous Single",
    artist: "Luke Roes",
    type: "Single",
    releaseDate: "2022-03-01",
    upc: "000000000004",
    catalogNumber: "LR-004",
    status: "Live",
    artworkFileKey: "https://placehold.co/400x400/4a4a4a/white?text=Single",
    artworkPublicUrl: "https://placehold.co/400x400/4a4a4a/white?text=Single",
    streamingLinks: {
      spotify: null,
      appleMusic: null,
      youtube: null,
      soundcloud: null,
      bandcamp: null,
    },
    distributor: null,
    distributionDate: null,
    releaseLabel: null,
    version: null,
    countriesOfFirstRelease: [],
    copyrightOwnerCountryOfNationality: null,
    tracks: [
      {
        id: 4001,
        trackNumber: 1,
        title: "Previous Single",
        duration: null,
        artist: "Luke Roes",
        isrc: null,
        song: {
          id: 5001,
          title: "Previous Single",
          lyrics: null,
          songwriters: null,
          iswc: null,
          genre: null,
          workType: null,
          language: null,
          copyrightYear: null,
          isInstrumental: null,
        },
        recording: {
          versionId: null,
          versionTitle: null,
          bpm: null,
          keySignature: null,
          timeSignature: null,
          studio: null,
          recordingDate: null,
          dateOfFirstRelease: null,
          countryOfMastering: null,
          countryOfRecording: null,
          primaryGenre: null,
          secondaryGenre: null,
          hasExplicitLyrics: null,
          labelName: null,
          credits: null,
          masterOwners: null,
          nonFeaturedPerformers: null,
        },
      },
    ],
  },
  {
    id: 54353,
    title: "Acoustic Sessions",
    artist: "Luke Roes",
    type: "EP",
    releaseDate: "2022-08-01",
    upc: "000000000005",
    catalogNumber: "LR-005",
    status: "Live",
    artworkFileKey: "https://placehold.co/400x400/5a5a5a/white?text=EP",
    artworkPublicUrl: "https://placehold.co/400x400/5a5a5a/white?text=EP",
    streamingLinks: {
      spotify: "https://open.spotify.com",
      appleMusic: null,
      youtube: null,
      soundcloud: null,
      bandcamp: null,
    },
    distributor: null,
    distributionDate: null,
    releaseLabel: null,
    version: null,
    countriesOfFirstRelease: [],
    copyrightOwnerCountryOfNationality: null,
    tracks: [
      {
        id: 5001,
        trackNumber: 1,
        title: "Unplugged Version",
        duration: null,
        artist: "Luke Roes",
        isrc: null,
        song: {
          id: 6001,
          title: "Unplugged Version",
          lyrics: null,
          songwriters: null,
          iswc: null,
          genre: null,
          workType: null,
          language: null,
          copyrightYear: null,
          isInstrumental: null,
        },
        recording: {
          versionId: null,
          versionTitle: null,
          bpm: null,
          keySignature: null,
          timeSignature: null,
          studio: null,
          recordingDate: null,
          dateOfFirstRelease: null,
          countryOfMastering: null,
          countryOfRecording: null,
          primaryGenre: null,
          secondaryGenre: null,
          hasExplicitLyrics: null,
          labelName: null,
          credits: null,
          masterOwners: null,
          nonFeaturedPerformers: null,
        },
      },
      {
        id: 5002,
        trackNumber: 2,
        title: "Stripped Down",
        duration: null,
        artist: "Luke Roes",
        isrc: null,
        song: {
          id: 6002,
          title: "Stripped Down",
          lyrics: null,
          songwriters: null,
          iswc: null,
          genre: null,
          workType: null,
          language: null,
          copyrightYear: null,
          isInstrumental: null,
        },
        recording: {
          versionId: null,
          versionTitle: null,
          bpm: null,
          keySignature: null,
          timeSignature: null,
          studio: null,
          recordingDate: null,
          dateOfFirstRelease: null,
          countryOfMastering: null,
          countryOfRecording: null,
          primaryGenre: null,
          secondaryGenre: null,
          hasExplicitLyrics: null,
          labelName: null,
          credits: null,
          masterOwners: null,
          nonFeaturedPerformers: null,
        },
      },
      {
        id: 5003,
        trackNumber: 3,
        title: "Raw Emotion",
        duration: null,
        artist: "Luke Roes",
        isrc: null,
        song: {
          id: 6003,
          title: "Raw Emotion",
          lyrics: null,
          songwriters: null,
          iswc: null,
          genre: null,
          workType: null,
          language: null,
          copyrightYear: null,
          isInstrumental: null,
        },
        recording: {
          versionId: null,
          versionTitle: null,
          bpm: null,
          keySignature: null,
          timeSignature: null,
          studio: null,
          recordingDate: null,
          dateOfFirstRelease: null,
          countryOfMastering: null,
          countryOfRecording: null,
          primaryGenre: null,
          secondaryGenre: null,
          hasExplicitLyrics: null,
          labelName: null,
          credits: null,
          masterOwners: null,
          nonFeaturedPerformers: null,
        },
      },
    ],
  },
];
